FROM node:lastest

LABEL author="Matthew Eddy"

ENV NODE_ENV=development
ENV PORT=8082

COPY     . /var/wwww
WORKDIR  /var/wwww

VOLUME   ["/var/www"]

RUN      npm install

EXPOSE $PORT

ENTRYPOINT ["npm", "run", "dev"]

